/** The 25 concept cards (PHASE-2 §4), in reading order; files live in content/concepts. */
export const CONCEPT_SLUGS = [
  "scalability-basics",
  "load-balancing",
  "caching-strategies",
  "cdn",
  "database-choice-sql-vs-nosql",
  "indexing",
  "replication",
  "sharding-partitioning",
  "consistent-hashing",
  "cap-pacelc",
  "consistency-models",
  "message-queues-vs-streams",
  "pub-sub",
  "idempotency",
  "rate-limiting-algorithms",
  "id-generation",
  "api-design-rest-grpc",
  "websockets-realtime",
  "object-storage-blobs",
  "search-indexes",
  "geo-indexing",
  "distributed-locks-consensus",
  "back-of-envelope-estimation",
  "fault-tolerance-retries",
  "observability",
] as const;
